# Generated by Django 5.2.7 on 2025-11-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cover_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone_Model', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Material', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Cover_Image', models.ImageField(blank=True, null=True, upload_to='cover image')),
                ('Quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
