# Generated by Django 5.2.7 on 2025-12-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
