# Generated by Django 5.2.7 on 2025-12-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_orderdb_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdb',
            old_name='Phone',
            new_name='total_amt',
        ),
        migrations.RemoveField(
            model_name='orderdb',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='orderdb',
            name='Appartment',
        ),
        migrations.RemoveField(
            model_name='orderdb',
            name='City',
        ),
        migrations.RemoveField(
            model_name='orderdb',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='orderdb',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='orderdb',
            name='Postcode',
        ),
        migrations.RemoveField(
            model_name='orderdb',
            name='Total_price',
        ),
        migrations.AddField(
            model_name='orderdb',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderdb',
            name='pincode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderdb',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderdb',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdb',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderdb',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderdb',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
